package com.hydroyura.dictinaryapp.stages.main;

public class MainStageConstants {

    public static String FOOTER_MAIN_ID = "FOOTER_MAIN";

    public static String HEADER_FIND_WORD_ID = "HEADER_FIND_WORD_ID";
    public static String FIELD_WORD_INPUT_ID = "FIELD_WORD_INPUT_ID";



    public static String BODY_ID = "BODY_ID";
    public static String BODY_SELECTED_WORD_ID = "BODY_SELECTED_WORD_ID";
    public static String BODY_WORDS_AUTOCOMPLETE_RESULT_ID = "BODY_WORDS_AUTOCOMPLETE_RESULT_ID";
    public static String BODY_WORDS_WORD_ADD_TITLE_ID = "BODY_WORDS_WORD_ADD_TITLE_ID";
    public static String BODY_WORDS_WORD_ADD_TITLE_TRANSCRIPTION_ID = "BODY_WORDS_WORD_ADD_TITLE_TRANSCRIPTION_ID";
    public static String BODY_WORDS_WORD_ADD_PRONUNCIATION_ID = "BODY_WORDS_WORD_ADD_PRONUNCIATION_ID";
    public static String BODY_TRANSLATION_VARIANTS_TABLE_ID = "BODY_TRANSLATION_VARIANTS_TABLE_ID";
    public static String BODY_TRANSLATION_VARIANTS_TABLE_BUTTON_ID = "BODY_TRANSLATION_VARIANTS_TABLE_BUTTON_ID";
    public static String BODY_BUTTON_ADD_CUSTOM_TRANSLATION_ID = "BODY_BUTTON_ADD_CUSTOM_TRANSLATION_ID";

    public static String ADD_TRANSLATE_DIALOG_TEXT_INPUT = "ADD_TRANSLATE_DIALOG_TEXT_INPUT";

    public static String FOOTER_ADD_WORD_ID = "FOOTER_ADD_WORD_ID";


}
